### PR TITLE
Make project reuse compliant

### PR DESCRIPTION
**Pull request by vpnachev**
**What this PR does / why we need it**:
Make project reuse compliant

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

### CODE REVIEW

**Comment by vpnachev** [comment]
@RaphaelVogel can you take another look, I had to fix third-party files copied in this repo with [af31931](https://github.com/gardener/gardener-extension-shoot-lakom-service/pull/71/commits/af31931706169bf745498f2c9e275a1df454e249)

**Comment by dimityrmirchev** [comment]
Should we also add the "Modifications Copyright" for files under `pkg/admission/`?

**Comment by dimityrmirchev** [comment]
And also maybe we should add the "Modification Copyright" for the following file [pkg/lakom/utils/cosign_utils.go](https://github.com/gardener/gardener-extension-shoot-lakom-service/blob/4144416ff53134f1e579630074e1c735cce91394/pkg/lakom/utils/cosign_utils.go#L2)

**Comment by dimityrmirchev** [comment]
For completeness the [Comment](https://dep-team.pages.debian.net/deps/dep5/#comment-field) field can include the HEAD commit from which the file was copied. That is just a suggestion.

**Review by dimityrmirchev — APPROVED** [review]
/lgtm

**Pull request merged**
